#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Humanbound
#
# Propose a change to the catalog (index.json and the README's table) as a pull request.
#
#   scripts/open_catalog_pr.sh "chore: regenerate index.json"
#
# main takes changes through pull requests only, from people and from CI alike. So a workflow
# that has regenerated the catalog does not push it: it opens a pull request, and a maintainer
# merges it. It starts the checks on that pull request itself, because a pull request opened
# with a workflow's own token does not start them.
#
# It keeps one catalog pull request open at most: the same change is not proposed twice, and a
# newer one replaces an older one.
set -euo pipefail

title="${1:?usage: open_catalog_pr.sh <title>}"
base="${CATALOG_BASE:-main}"

git add index.json README.md
if git diff --cached --quiet; then
  echo "The catalog has not changed."
  exit 0
fi

git fetch --quiet origin '+refs/heads/catalog/*:refs/remotes/origin/catalog/*' || true
open=$(gh pr list --state open --base "$base" --json number,headRefName \
  --jq '.[] | select(.headRefName | startswith("catalog/")) | "\(.number) \(.headRefName)"')

while read -r number head; do
  [ -n "$number" ] || continue
  if git diff --cached --quiet "origin/$head" -- index.json README.md 2>/dev/null; then
    echo "This change is already proposed in #$number."
    exit 0
  fi
done <<<"$open"

branch="catalog/${GITHUB_RUN_ID:-manual}-${GITHUB_RUN_ATTEMPT:-1}"
git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
git switch --quiet -c "$branch"
git commit --quiet -s -m "$title"
git push --quiet origin "$branch"

if ! gh pr create --base "$base" --head "$branch" --title "$title" --body \
"Generated by CI: \`index.json\` and the catalog table in \`README.md\`, as \`scripts/build_index.py\` writes them. Nothing else changes.

\`main\` takes changes through pull requests only, so CI proposes the catalog here instead of pushing it. A maintainer merges it."
then
  # The branch is pushed, so nothing is lost: only the pull request is missing.
  echo "::error::CI could not open the pull request. The catalog update is on the branch" \
    "'$branch': open a pull request from it by hand. To let CI open it, an organisation admin" \
    "allows it under Settings, Actions, General, Workflow permissions:" \
    "'Allow GitHub Actions to create and approve pull requests'."
  exit 1
fi

# A pull request opened with this token starts no workflow, so start the required checks here.
gh workflow run validate.yml --ref "$branch"
gh workflow run dco.yml --ref "$branch"

while read -r number head; do
  [ -n "$number" ] || continue
  gh pr close "$number" --delete-branch --comment "Replaced by a newer catalog update."
done <<<"$open"
